apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-consumer
  template:
    metadata:
      labels:
        app: blog-consumer
    spec:
      containers:
      - name: consumer
        image: blog-consumer:latest
